logging:
  level:
    com:
      cognizant: debug
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql: trace
      springframework:
        web: DEBUG
  pattern:
    console: '%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M %4L %m%n'
server:
  port: 9000
spring:
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: always
    password: ''
    url: jdbc:h2:mem:productdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

